extends: ./config.yaml
configs:
  uriGroup:
    portal:
      uri: http://localhost:4200/portal
      type: redirect
    site:
      uri: http://localhost:4200/site
      type: redirect
    api:
      uri: http://localhost:4200/api
  redis:
    host: http://127.0.0.1
    port: 1234
  mysql:
    host: http://localhost
    port: 3306
    database: mysql
    user: root
    password: 2w3e4r5t
  cluster:
    maxCpuNum: 1
  gzip:
    enabled: false
  startMode: app
