configs:
  name: ews-server
  envMode: prod
  port: 3000
  uriGroup:
    portal:
      uri: client
      token: portal
      type: render
    site:
      uri: site
      token: site
      type: render
    api:
      uri: api
      token: api
      type: redirect
  redis:
    host: http://127.0.0.1
    port: 1234
  mysql:
    host: 127.0.0.1
    port: 3306
    database: mysql
    user: root
    password: 123456
    synchronize: false
  cluster:
    maxCpuNum: null
  gzip:
    enabled: true
  startMode: app
